name: kisan_salahkaar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^16.2.1
  lucide_flutter: ^0.544.0
  image_picker: ^1.1.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_ai: ^3.2.0
  flutter_riverpod: ^2.5.1


dev_-dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
